[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.15"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_hack = "4uYHTyZzVZjzJh4Dvh8R1hE779SxPbZj7ZMTTHAWTQAn"

[programs.devnet]
proof_of_hack = "4uYHTyZzVZjzJh4Dvh8R1hE779SxPbZj7ZMTTHAWTQAn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 30000

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
